name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Javascript Action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Henry Megwai
          #add another step name here
      - name: Log Greeting Time
        run: echo "$GITHUB_STATE"
