name: Container

on: 
  push:
    branches:
      - "dev"

jobs: 
   node-docker:
     runs-on: ubuntu-latest
     container:
        image: node:16-alpine3.15
     steps:
      - name: Log node version
        run: |
            node -v
            cat /etc/os-release